// vite.config.ts
// Purpose: Vite build configuration for RoundTable.
//
// v0.12.0 Checkpoint K — PWA implementation bundle.
//   Adds vite-plugin-pwa for static-site PWA support:
//     * service worker generated by Workbox
//     * web app manifest emitted into dist/
//     * pre-cache for the app shell (HTML, JS, CSS, fonts, icons)
//     * NO runtimeCaching: RoundTable makes zero network requests at
//       runtime, so there is no third bucket of fetches to plan for.
//   The update flow is operator-prompted (registerType: 'prompt'),
//   not auto-updating — see src/main.tsx and src/components/PwaUpdateBanner.tsx.
//
// base: './' is preserved so the build is portable to any static host
// (Netlify is the first target; the relative-path output works at any
// path prefix without code changes).

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  base: './',
  plugins: [
    react(),
    VitePWA({
      // Operator-prompted update. We render a RoundTable-styled banner
      // when a new SW is waiting; the operator decides when to reload.
      // 'autoUpdate' would reload silently and destroy mid-import state.
      registerType: 'prompt',
      // We register the SW ourselves in src/main.tsx so we can wire
      // the update banner via useRegisterSW(). The plugin's automatic
      // injection would conflict with that.
      injectRegister: false,
      // Assets in /public/ that should be precached alongside the
      // generated bundle. The icons are referenced from the manifest
      // and the HTML head; precaching ensures offline availability.
      includeAssets: [
        'favicon.png',
        'apple-touch-icon.png',
      ],
      manifest: {
        // The `id` anchors the install entry; keep stable across versions.
        id: '/?source=pwa',
        name: 'RoundTable',
        short_name: 'RoundTable',
        description:
          'Local-first multi-model coordination cockpit — manual ' +
          'copy/paste workflow for AI roundtables. No backend, no API, ' +
          'no automation.',
        // start_url and scope are relative so the PWA installs cleanly
        // at any subpath (root on Netlify, /roundtable/ on a subpath
        // host). The relative './' resolves to the manifest's URL.
        start_url: './',
        scope: './',
        display: 'standalone',
        orientation: 'any',
        background_color: '#0d0f11',
        theme_color: '#0d0f11',
        categories: ['productivity', 'developer', 'utilities'],
        icons: [
          {
            src: 'icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'icon-192-maskable.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable',
          },
          {
            src: 'icon-512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Precache everything emitted into dist that the app needs to
        // boot offline. No `runtimeCaching` — see header comment.
        globPatterns: ['**/*.{js,css,html,png,svg,woff2,webmanifest}'],
        // Skip waiting / claim clients are handled by the prompt
        // strategy; we deliberately do NOT set skipWaiting: true here.
        // The SW activates only after the operator confirms via the
        // update banner.
        // Navigation fallback: route any in-scope navigation to the
        // app shell so deep-link reloads work offline.
        navigateFallback: 'index.html',
        // Reasonable cleanup: drop stale precaches when a new version
        // activates.
        cleanupOutdatedCaches: true,
      },
      // dev server: keep the PWA off in dev so the SW doesn't cache
      // hot-reload assets. Production-only is the standard pattern.
      devOptions: {
        enabled: false,
      },
    }),
  ],
});
